notifications:
  email: false
  slack:
    secure: XaEDRvwiOYrJF1B0fK1/QUXOOoPnYshUWdJ3XhRZfULhlrQS7M++yCJBcXbILYtFU9WO651t/Od4efeJaSL2UR60IrEaaH7cr5QH6I1jh/LsNro7aMRMNjgBISYBazDSPDULk4Czye5lD1hx3SnwIVJ0DFtQIW7P4A/sY1miqvU=
sudo: false
language: java
install:
  - echo "<settings><mirrors><mirror><id>sonatype-mirror</id><url>http://artifactory.eanadev.org/artifactory/ext-snapshot-local</url><mirrorOf>sonatype-nexus-snapshots</mirrorOf></mirror></mirrors></settings>" > ~/settings.xml
  - mvn install -s ~/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
  - oraclejdk8
after_success:
  - mvn clean cobertura:cobertura coveralls:report
